name: Lighthouse CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Start preview server
        run: |
          nohup npm run preview -- --port 4173 --host 127.0.0.1 >/dev/null 2>&1 &

      - name: Wait for server
        run: npx wait-on http://127.0.0.1:4173

      - name: Run Lighthouse
        run: |
          mkdir -p reports
          npx lighthouse http://127.0.0.1:4173 \
            --output=json --output=html \
            --output-path=./reports/lighthouse \
            --quiet \
            --chrome-flags="--headless=new"

      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-report
          path: reports

